# -*- coding: utf-8 -*-
"""Strategy-level backtester.

Scans historical daily data, applies ``quantitative_rules`` from each strategy
YAML, generates buy/sell signals, and evaluates each signal using the existing
``BacktestEngine``.

Usage::

    from src.core.strategy_backtester import StrategyBacktester

    backtester = StrategyBacktester()
    result = backtester.backtest_strategy(skill, code="600519", df=daily_df)
    print(result.win_rate, result.profit_factor)
"""

import logging
from dataclasses import dataclass, field
from datetime import date, timedelta
from typing import Any, Dict, List, Optional

import numpy as np
import pandas as pd

from src.core.backtest_engine import BacktestEngine, EvaluationConfig
from src.core.rule_evaluator import ConditionResult, EvaluationResult, RuleEvaluator

logger = logging.getLogger(__name__)

# Minimum rows needed to compute indicators (MA60 needs 60 bars)
_MIN_WARMUP_BARS = 60


@dataclass
class StrategySignal:
    """A signal generated by a strategy on a specific date."""

    strategy_name: str
    code: str
    signal_date: date
    direction: str           # "buy" or "sell"
    entry_price: float
    stop_loss: Optional[float] = None
    take_profit: Optional[float] = None
    atr_14: float = 0.0
    conditions_detail: Optional[List[Dict]] = None


@dataclass
class SignalEvaluation:
    """Evaluation result for a single signal."""

    signal: StrategySignal
    eval_status: str          # "completed" / "insufficient_data"
    outcome: Optional[str] = None   # "win" / "loss" / "neutral"
    return_pct: Optional[float] = None
    exit_reason: Optional[str] = None
    holding_days: Optional[int] = None
    direction_correct: Optional[bool] = None


@dataclass
class StrategyBacktestResult:
    """Aggregated backtest result for one strategy."""

    strategy_name: str
    total_signals: int = 0
    evaluated_count: int = 0
    win_count: int = 0
    loss_count: int = 0
    neutral_count: int = 0
    win_rate: Optional[float] = None
    avg_return_pct: Optional[float] = None
    max_drawdown_pct: Optional[float] = None
    profit_factor: Optional[float] = None
    sharpe_ratio: Optional[float] = None
    avg_holding_days: Optional[float] = None
    stop_loss_trigger_rate: Optional[float] = None
    take_profit_trigger_rate: Optional[float] = None
    evaluations: List[SignalEvaluation] = field(default_factory=list)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "strategy_name": self.strategy_name,
            "total_signals": self.total_signals,
            "evaluated_count": self.evaluated_count,
            "win_count": self.win_count,
            "loss_count": self.loss_count,
            "neutral_count": self.neutral_count,
            "win_rate": round(self.win_rate, 4) if self.win_rate is not None else None,
            "avg_return_pct": round(self.avg_return_pct, 4) if self.avg_return_pct is not None else None,
            "max_drawdown_pct": round(self.max_drawdown_pct, 4) if self.max_drawdown_pct is not None else None,
            "profit_factor": round(self.profit_factor, 4) if self.profit_factor is not None else None,
            "sharpe_ratio": round(self.sharpe_ratio, 4) if self.sharpe_ratio is not None else None,
            "avg_holding_days": round(self.avg_holding_days, 2) if self.avg_holding_days is not None else None,
            "stop_loss_trigger_rate": (
                round(self.stop_loss_trigger_rate, 4) if self.stop_loss_trigger_rate is not None else None
            ),
            "take_profit_trigger_rate": (
                round(self.take_profit_trigger_rate, 4) if self.take_profit_trigger_rate is not None else None
            ),
        }


class StrategyBacktester:
    """Backtest a single strategy against historical data."""

    def __init__(
        self,
        eval_config: Optional[EvaluationConfig] = None,
    ):
        self.eval_config = eval_config or EvaluationConfig(eval_window_days=10, neutral_band_pct=2.0)

    def scan_signals(
        self,
        strategy_name: str,
        buy_conditions: List[Dict[str, Any]],
        code: str,
        df: pd.DataFrame,
        holding_days: int = 10,
        stop_loss_atr_mult: float = 2.0,
        take_profit_atr_mult: float = 3.0,
    ) -> List[StrategySignal]:
        """Scan historical data for buy signals matching strategy rules.

        Args:
            strategy_name: Strategy identifier.
            buy_conditions: Structured conditions from quantitative_rules.buy_conditions.
            code: Stock code.
            df: Daily OHLCV DataFrame with columns: date, open, high, low, close, volume.
                Index must be numeric, sorted by date ascending.
            holding_days: Default holding period for signal cooldown.
            stop_loss_atr_mult: ATR multiplier for stop loss.
            take_profit_atr_mult: ATR multiplier for take profit.

        Returns:
            List of StrategySignal instances.
        """
        if df is None or len(df) < _MIN_WARMUP_BARS + 5:
            logger.debug("Insufficient data for %s/%s: %d rows", strategy_name, code, len(df) if df is not None else 0)
            return []

        signals: List[StrategySignal] = []
        last_signal_idx = -holding_days  # allow first signal immediately

        # Pre-compute indicators for each row using a rolling window
        indicator_rows = self._compute_indicators_batch(df)

        for i in range(_MIN_WARMUP_BARS, len(df)):
            # Cooldown: skip if within holding_days of last signal
            if (i - last_signal_idx) < holding_days:
                continue

            indicators = indicator_rows.get(i)
            if indicators is None:
                continue

            # Evaluate buy conditions
            result = RuleEvaluator.evaluate(buy_conditions, indicators)
            if not result.all_passed:
                continue

            # Extract entry price and ATR
            row = df.iloc[i]
            entry_price = float(row.get("close", 0))
            atr = float(indicators.get("atr_14", 0))
            if entry_price <= 0:
                continue

            # Calculate stop loss / take profit from ATR
            sl = entry_price - atr * stop_loss_atr_mult if atr > 0 else None
            tp = entry_price + atr * take_profit_atr_mult if atr > 0 else None

            # Get signal date
            signal_date = self._get_date(row)
            if signal_date is None:
                continue

            signals.append(StrategySignal(
                strategy_name=strategy_name,
                code=code,
                signal_date=signal_date,
                direction="buy",
                entry_price=entry_price,
                stop_loss=sl,
                take_profit=tp,
                atr_14=atr,
                conditions_detail=[d.to_dict() for d in result.details],
            ))
            last_signal_idx = i

        logger.info(
            "Strategy '%s' on %s: scanned %d bars, found %d signals",
            strategy_name, code, len(df), len(signals),
        )
        return signals

    def evaluate_signals(
        self,
        signals: List[StrategySignal],
        df: pd.DataFrame,
    ) -> List[SignalEvaluation]:
        """Evaluate each signal using BacktestEngine.evaluate_single().

        Args:
            signals: List of signals to evaluate.
            df: Daily OHLCV DataFrame (same as used for scanning).

        Returns:
            List of SignalEvaluation instances.
        """
        evaluations: List[SignalEvaluation] = []
        date_to_idx = self._build_date_index(df)

        for sig in signals:
            idx = date_to_idx.get(sig.signal_date)
            if idx is None:
                evaluations.append(SignalEvaluation(
                    signal=sig, eval_status="insufficient_data",
                ))
                continue

            # Get forward bars
            forward_start = idx + 1
            forward_end = forward_start + self.eval_config.eval_window_days
            if forward_end > len(df):
                evaluations.append(SignalEvaluation(
                    signal=sig, eval_status="insufficient_data",
                ))
                continue

            forward_df = df.iloc[forward_start:forward_end]
            forward_bars = []
            for _, row in forward_df.iterrows():
                bar_date = self._get_date(row)
                forward_bars.append(type("Bar", (), {
                    "date": bar_date,
                    "high": float(row.get("high", 0)),
                    "low": float(row.get("low", 0)),
                    "close": float(row.get("close", 0)),
                })())

            if len(forward_bars) < self.eval_config.eval_window_days:
                evaluations.append(SignalEvaluation(
                    signal=sig, eval_status="insufficient_data",
                ))
                continue

            # Use existing BacktestEngine
            try:
                result = BacktestEngine.evaluate_single(
                    operation_advice="买入" if sig.direction == "buy" else "卖出",
                    analysis_date=sig.signal_date,
                    start_price=sig.entry_price,
                    forward_bars=forward_bars,
                    stop_loss=sig.stop_loss,
                    take_profit=sig.take_profit,
                    config=self.eval_config,
                )
            except Exception as exc:
                logger.warning("BacktestEngine error for %s/%s at %s: %s", sig.strategy_name, sig.code, sig.signal_date, exc)
                evaluations.append(SignalEvaluation(
                    signal=sig, eval_status="error",
                ))
                continue

            evaluations.append(SignalEvaluation(
                signal=sig,
                eval_status=result.get("eval_status", "error"),
                outcome=result.get("outcome"),
                return_pct=result.get("simulated_return_pct"),
                exit_reason=result.get("simulated_exit_reason"),
                holding_days=result.get("first_hit_trading_days"),
                direction_correct=result.get("direction_correct"),
            ))

        return evaluations

    def aggregate_results(
        self,
        strategy_name: str,
        evaluations: List[SignalEvaluation],
    ) -> StrategyBacktestResult:
        """Aggregate individual evaluations into summary metrics."""
        result = StrategyBacktestResult(strategy_name=strategy_name, evaluations=evaluations)
        result.total_signals = len(evaluations)

        completed = [e for e in evaluations if e.eval_status == "completed"]
        result.evaluated_count = len(completed)

        if not completed:
            return result

        result.win_count = sum(1 for e in completed if e.outcome == "win")
        result.loss_count = sum(1 for e in completed if e.outcome == "loss")
        result.neutral_count = sum(1 for e in completed if e.outcome == "neutral")

        result.win_rate = result.win_count / result.evaluated_count if result.evaluated_count > 0 else None

        # Average return
        returns = [e.return_pct for e in completed if e.return_pct is not None]
        if returns:
            result.avg_return_pct = sum(returns) / len(returns)

            # Max drawdown (simple: worst single trade)
            result.max_drawdown_pct = min(returns) if returns else None

            # Profit factor
            gains = sum(r for r in returns if r > 0)
            losses = abs(sum(r for r in returns if r < 0))
            result.profit_factor = gains / losses if losses > 0 else (float("inf") if gains > 0 else 0)

            # Sharpe ratio (simplified: mean/std of returns)
            if len(returns) >= 2:
                std = float(np.std(returns))
                if std > 0:
                    result.sharpe_ratio = float(np.mean(returns)) / std
                else:
                    result.sharpe_ratio = 0.0

        # Average holding days
        hold_days = [e.holding_days for e in completed if e.holding_days is not None]
        if hold_days:
            result.avg_holding_days = sum(hold_days) / len(hold_days)

        # Stop loss / take profit trigger rates
        sl_count = sum(1 for e in completed if e.exit_reason == "stop_loss")
        tp_count = sum(1 for e in completed if e.exit_reason == "take_profit")
        result.stop_loss_trigger_rate = sl_count / result.evaluated_count if result.evaluated_count > 0 else None
        result.take_profit_trigger_rate = tp_count / result.evaluated_count if result.evaluated_count > 0 else None

        return result

    def backtest_strategy(
        self,
        strategy_name: str,
        buy_conditions: List[Dict[str, Any]],
        code: str,
        df: pd.DataFrame,
        holding_days: int = 10,
        stop_loss_atr_mult: float = 2.0,
        take_profit_atr_mult: float = 3.0,
    ) -> StrategyBacktestResult:
        """Full pipeline: scan → evaluate → aggregate."""
        signals = self.scan_signals(
            strategy_name=strategy_name,
            buy_conditions=buy_conditions,
            code=code,
            df=df,
            holding_days=holding_days,
            stop_loss_atr_mult=stop_loss_atr_mult,
            take_profit_atr_mult=take_profit_atr_mult,
        )
        evaluations = self.evaluate_signals(signals, df)
        return self.aggregate_results(strategy_name, evaluations)

    # ---- Internal helpers ----

    def _compute_indicators_batch(self, df: pd.DataFrame) -> Dict[int, Dict[str, Any]]:
        """Compute indicators for all rows in the dataframe.

        Uses a lightweight approach: compute rolling indicators directly
        from the DataFrame instead of calling StockAnalyzer for each row
        (which would be too slow for backtesting).
        """
        indicators: Dict[int, Dict[str, Any]] = {}

        if len(df) < _MIN_WARMUP_BARS:
            return indicators

        close = df["close"].values.astype(float)
        high = df["high"].values.astype(float)
        low = df["low"].values.astype(float)
        volume = df["volume"].values.astype(float) if "volume" in df.columns else np.ones(len(df))

        # Moving averages
        ma5 = pd.Series(close).rolling(5).mean().values
        ma10 = pd.Series(close).rolling(10).mean().values
        ma20 = pd.Series(close).rolling(20).mean().values
        ma60 = pd.Series(close).rolling(60).mean().values

        # Volume ratio
        vol_ma5 = pd.Series(volume).rolling(5).mean().values

        # RSI (12-period)
        rsi_12 = self._calc_rsi(close, 12)

        # MACD
        dif, dea, macd_bar = self._calc_macd(close)

        # ATR (14-period)
        atr_14 = self._calc_atr(high, low, close, 14)

        # KDJ
        kdj_k, kdj_d, kdj_j = self._calc_kdj(high, low, close)

        for i in range(_MIN_WARMUP_BARS, len(df)):
            if np.isnan(ma20[i]) or np.isnan(ma5[i]):
                continue

            # Trend status
            trend_status = self._determine_trend(ma5[i], ma10[i], ma20[i])

            # Bias from MA5
            bias_ma5 = ((close[i] - ma5[i]) / ma5[i] * 100) if ma5[i] > 0 else 0

            # Volume ratio
            vol_ratio = (volume[i] / vol_ma5[i]) if vol_ma5[i] > 0 else 1.0

            # Volume status
            price_change = close[i] - close[i - 1] if i > 0 else 0
            volume_status = self._determine_volume_status(vol_ratio, price_change)

            # Support
            support_ma5 = abs(close[i] - ma5[i]) / close[i] < 0.01 if close[i] > 0 else False
            support_ma10 = abs(close[i] - ma10[i]) / close[i] < 0.02 if close[i] > 0 else False

            # MACD status
            macd_status = self._determine_macd_status(dif[i], dea[i], macd_bar[i],
                                                       dif[i - 1] if i > 0 else 0,
                                                       dea[i - 1] if i > 0 else 0)

            # RSI status
            rsi_val = rsi_12[i] if not np.isnan(rsi_12[i]) else 50.0

            # ATR
            atr_val = atr_14[i] if not np.isnan(atr_14[i]) else 0
            atr_ratio = (atr_val / close[i] * 100) if close[i] > 0 else 0

            # ATR trend
            atr_trend = "平稳"
            if i >= 5 and not np.isnan(atr_14[i - 5]):
                atr_change = (atr_val - atr_14[i - 5]) / atr_14[i - 5] if atr_14[i - 5] > 0 else 0
                if atr_change < -0.1:
                    atr_trend = "收缩"
                elif atr_change > 0.1:
                    atr_trend = "扩大"

            # MA20 direction
            ma20_direction = "走平"
            if i >= 5 and not np.isnan(ma20[i - 5]):
                ma20_change = (ma20[i] - ma20[i - 5]) / ma20[i - 5] if ma20[i - 5] > 0 else 0
                if ma20_change > 0.005:
                    ma20_direction = "上行"
                elif ma20_change < -0.005:
                    ma20_direction = "下行"

            # Trend strength (0-100)
            trend_strength = self._calc_trend_strength(ma5[i], ma10[i], ma20[i], close[i])

            # KDJ signal
            kdj_signal = "neutral"
            k_val = kdj_k[i] if not np.isnan(kdj_k[i]) else 50
            d_val = kdj_d[i] if not np.isnan(kdj_d[i]) else 50
            j_val = kdj_j[i] if not np.isnan(kdj_j[i]) else 50
            if i > 0 and not np.isnan(kdj_k[i - 1]):
                k_prev = kdj_k[i - 1]
                d_prev = kdj_d[i - 1]
                if k_prev <= d_prev and k_val > d_val:
                    kdj_signal = "golden_cross"
                elif k_prev >= d_prev and k_val < d_val:
                    kdj_signal = "dead_cross"

            indicators[i] = {
                "trend_status": trend_status,
                "trend_strength": trend_strength,
                "ma5": ma5[i],
                "ma10": ma10[i],
                "ma20": ma20[i],
                "ma60": ma60[i] if not np.isnan(ma60[i]) else 0,
                "current_price": close[i],
                "bias_ma5": bias_ma5,
                "bias_ma10": ((close[i] - ma10[i]) / ma10[i] * 100) if ma10[i] > 0 else 0,
                "volume_ratio_5d": vol_ratio,
                "volume_status": volume_status,
                "support_ma5": support_ma5,
                "support_ma10": support_ma10,
                "macd_status": macd_status,
                "macd_dif": dif[i],
                "macd_dea": dea[i],
                "macd_bar": macd_bar[i],
                "rsi_12": rsi_val,
                "rsi_6": rsi_val,  # simplified
                "atr_14": atr_val,
                "atr_ratio": atr_ratio,
                "atr_trend": atr_trend,
                "ma20_direction": ma20_direction,
                "kdj_k": k_val,
                "kdj_d": d_val,
                "kdj_j": j_val,
                "kdj_signal": kdj_signal,
            }

        return indicators

    @staticmethod
    def _determine_trend(ma5: float, ma10: float, ma20: float) -> str:
        if ma5 > ma10 > ma20:
            gap = (ma5 - ma20) / ma20 if ma20 > 0 else 0
            return "强势多头" if gap > 0.03 else "多头排列"
        elif ma5 > ma10 and ma10 < ma20:
            return "弱势多头"
        elif ma5 < ma10 < ma20:
            gap = (ma20 - ma5) / ma20 if ma20 > 0 else 0
            return "强势空头" if gap > 0.03 else "空头排列"
        elif ma5 < ma10 and ma10 > ma20:
            return "弱势空头"
        return "盘整"

    @staticmethod
    def _determine_volume_status(vol_ratio: float, price_change: float) -> str:
        if vol_ratio > 1.5 and price_change > 0:
            return "放量上涨"
        elif vol_ratio > 1.5 and price_change < 0:
            return "放量下跌"
        elif vol_ratio < 0.7 and price_change > 0:
            return "缩量上涨"
        elif vol_ratio < 0.7 and price_change <= 0:
            return "缩量回调"
        return "量能正常"

    @staticmethod
    def _determine_macd_status(dif: float, dea: float, bar: float,
                                dif_prev: float, dea_prev: float) -> str:
        if dif_prev <= dea_prev and dif > dea:
            return "GOLDEN_CROSS"
        elif dif_prev >= dea_prev and dif < dea:
            return "DEAD_CROSS"
        elif bar > 0:
            return "BULLISH"
        return "BEARISH"

    @staticmethod
    def _calc_trend_strength(ma5: float, ma10: float, ma20: float, price: float) -> float:
        """Simple trend strength score 0-100."""
        score = 50.0
        if ma5 > ma10:
            score += 15
        elif ma5 < ma10:
            score -= 15
        if ma10 > ma20:
            score += 15
        elif ma10 < ma20:
            score -= 15
        if price > ma20:
            score += 10
        elif price < ma20:
            score -= 10
        # Spread
        if ma20 > 0:
            spread = abs(ma5 - ma20) / ma20 * 100
            score += min(spread * 2, 10)
        return max(0, min(100, score))

    @staticmethod
    def _calc_rsi(close: np.ndarray, period: int = 14) -> np.ndarray:
        deltas = np.diff(close, prepend=close[0])
        gains = np.where(deltas > 0, deltas, 0)
        losses = np.where(deltas < 0, -deltas, 0)
        avg_gain = pd.Series(gains).ewm(span=period, adjust=False).mean().values
        avg_loss = pd.Series(losses).ewm(span=period, adjust=False).mean().values
        rs = np.divide(avg_gain, avg_loss, out=np.ones_like(avg_gain), where=avg_loss > 0)
        rsi = 100 - (100 / (1 + rs))
        return rsi

    @staticmethod
    def _calc_macd(close: np.ndarray,
                   fast: int = 12, slow: int = 26, signal: int = 9):
        s = pd.Series(close)
        ema_fast = s.ewm(span=fast, adjust=False).mean()
        ema_slow = s.ewm(span=slow, adjust=False).mean()
        dif = (ema_fast - ema_slow).values
        dea = pd.Series(dif).ewm(span=signal, adjust=False).mean().values
        bar = 2 * (dif - dea)
        return dif, dea, bar

    @staticmethod
    def _calc_atr(high: np.ndarray, low: np.ndarray, close: np.ndarray,
                  period: int = 14) -> np.ndarray:
        tr = np.maximum(
            high - low,
            np.maximum(
                np.abs(high - np.roll(close, 1)),
                np.abs(low - np.roll(close, 1)),
            ),
        )
        tr[0] = high[0] - low[0]
        atr = pd.Series(tr).rolling(period).mean().values
        return atr

    @staticmethod
    def _calc_kdj(high: np.ndarray, low: np.ndarray, close: np.ndarray,
                  n: int = 9) -> tuple:
        """Calculate KDJ indicator."""
        k = np.full(len(close), 50.0)
        d = np.full(len(close), 50.0)
        j = np.full(len(close), 50.0)

        for i in range(n - 1, len(close)):
            hn = np.max(high[i - n + 1: i + 1])
            ln = np.min(low[i - n + 1: i + 1])
            if hn == ln:
                rsv = 50.0
            else:
                rsv = (close[i] - ln) / (hn - ln) * 100
            k[i] = 2 / 3 * (k[i - 1] if i > 0 else 50) + 1 / 3 * rsv
            d[i] = 2 / 3 * (d[i - 1] if i > 0 else 50) + 1 / 3 * k[i]
            j[i] = 3 * k[i] - 2 * d[i]

        return k, d, j

    @staticmethod
    def _get_date(row) -> Optional[date]:
        """Extract date from a DataFrame row."""
        for col in ("date", "trade_date", "Date"):
            val = row.get(col) if isinstance(row, dict) else getattr(row, col, None)
            if val is not None:
                if isinstance(val, date):
                    return val
                if isinstance(val, pd.Timestamp):
                    return val.date()
                try:
                    return pd.to_datetime(str(val)).date()
                except (ValueError, TypeError):
                    pass
        # Try index
        if hasattr(row, "name") and isinstance(row.name, (date, pd.Timestamp)):
            return row.name if isinstance(row.name, date) else row.name.date()
        return None

    @staticmethod
    def _build_date_index(df: pd.DataFrame) -> Dict[date, int]:
        """Build a mapping from date -> row index."""
        date_map: Dict[date, int] = {}
        for i in range(len(df)):
            row = df.iloc[i]
            d = StrategyBacktester._get_date(row)
            if d is not None:
                date_map[d] = i
        return date_map
